### PR TITLE
fix: make count_entities test work with igraph current version

### LINKED ISSUE #500: Test relies on specific output from sample_islands() for given seed
The "counting the number of strongly connected components is possible" test currently relies on igraph's `sample_islands()` function returning a specific output for a specific seed. 

https://github.com/rich-iannone/DiagrammeR/blob/main/tests/testthat/test-count_entities.R#L129

We do not guarantee that the output of such stochastic functions won't change across versions (for the same seed). Can you please refactor the test not to rely on this? In an upcoming version of igraph, `sample_islands()` will change, causing this test to fail.

### PR DESCRIPTION
**Pull request by maelle**
Fix #500

However it makes the example a bit ridiculous?!

@krlmlr

### CODE REVIEW

File: tests/testthat/test-count_entities.R [hunk 1]
```diff
@@ -128,10 +128,9 @@ test_that("counting the number of strongly connected components is possible", {
      create_graph() %>%
      add_islands_graph(
        n_islands = 4,
-       island_size = 10,
-       p = 1 / 5,
-       edges_between = 1,
-       set_seed = 23)
+       island_size = 1,
```
Comment (maelle) [inline tests/testthat/test-count_entities.R:131]: with this if I follow correctly we created 4 unconnected islands of 1 elements each so there are 4 strongly connected elements. however are they connected to themselves then?

Comment (rich-iannone) [reply tests/testthat/test-count_entities.R:131]: I think we should go with this for now and solve the immediate problem (of fixing a revdep failure for igraph). I can always revise the tests later.

**Comment by rich-iannone** [comment]
Thanks @maelle , I'll merge right now!
